# Generated by Django 5.1.3 on 2024-11-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_customuser_reviews_parcel_origin_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
