# Generated by Django 5.0.7 on 2024-11-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_customuser_reviews_parcel_origin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="parcel",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
